// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package guardian

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	guardianMapGuardianM = "guardian_m"
	guardianMapModeMap   = "mode_map"
	guardianProgGuardian = "guardian"
	guardianVarMODE      = "MODE"
)

// loadGuardian returns the embedded CollectionSpec for guardian.
func loadGuardian() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GuardianBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load guardian: %w", err)
	}

	return spec, err
}

// loadGuardianObjects loads guardian and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*guardianObjects
//	*guardianPrograms
//	*guardianMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGuardianObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadGuardian()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// guardianSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianSpecs struct {
	guardianProgramSpecs
	guardianMapSpecs
	guardianVariableSpecs
}

// guardianProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianProgramSpecs struct {
	Guardian *ebpf.ProgramSpec `ebpf:"guardian"`
}

// guardianMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianMapSpecs struct {
	GuardianM *ebpf.MapSpec `ebpf:"guardian_m"`
	ModeMap   *ebpf.MapSpec `ebpf:"mode_map"`
}

// guardianVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardianVariableSpecs struct {
	MODE *ebpf.VariableSpec `ebpf:"MODE"`
}

// guardianObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianObjects struct {
	guardianPrograms
	guardianMaps
	guardianVariables
}

func (o *guardianObjects) Close() error {
	return _GuardianClose(
		&o.guardianPrograms,
		&o.guardianMaps,
	)
}

// guardianMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianMaps struct {
	GuardianM *ebpf.Map `ebpf:"guardian_m"`
	ModeMap   *ebpf.Map `ebpf:"mode_map"`
}

func (m *guardianMaps) Close() error {
	return _GuardianClose(
		m.GuardianM,
		m.ModeMap,
	)
}

// guardianVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianVariables struct {
	MODE *ebpf.Variable `ebpf:"MODE"`
}

// guardianPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGuardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardianPrograms struct {
	Guardian *ebpf.Program `ebpf:"guardian"`
}

func (p *guardianPrograms) Close() error {
	return _GuardianClose(
		p.Guardian,
	)
}

func _GuardianClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed guardian_bpfel.o
var _GuardianBytes []byte
